# Basic CI workflow

name: Github Workflow

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allow this workflow to run manually from the Actions tab
  workflow_dispatch:

jobs:
  # The "build" job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      # Check-out my repository under $GITHUB_WORKSPACE, so the jobs can access it
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      
      # Echo a start message
      - name: Echo a start message
        run: echo Starting Checkov Testing
          
      # Runs an IaC Checkov test
      - name: Test with Checkov
        run: |
          pip install checkov
          checkov -d .
      
      # Upload IaC Checkov test results
      - name: Upload Checkov test results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-test-results
          path: results.json
